### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by stramel** [Polymer/gen-typescript-declarations#95]
Tool doesn't appear to run on windows. Ran fine on my linux PC though.

**Comment by aomarks** [comment]
Can you give any error log?

**Comment by stramel** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'update-types' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'preupdate-types', 'update-types', 'postupdate-types' ]
5 info lifecycle @polymer/marked-element@~preupdate-types: @polymer/marked-element@
6 info lifecycle @polymer/marked-element@~update-types: @polymer/marked-element@
7 verbose lifecycle @polymer/marked-element@~update-types: unsafe-perm in lifecycle true
8 verbose lifecycle @polymer/marked-element@~update-types: PATH: C:\Users\stramel\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\stramel\Projects\GitHub\marked-element\node_modules\.bin;C:\Users\stramel\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\stramel\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Users\stramel\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Skype\Phone;C:\Users\stramel\AppData\Local\Microsoft\WindowsApps;C:\Users\stramel\AppData\Local\atom\bin;C:\Users\stramel\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\stramel\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\cygwin64\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle @polymer/marked-element@~update-types: CWD: C:\Users\stramel\Projects\GitHub\marked-element
10 silly lifecycle @polymer/marked-element@~update-types: Args: [ '/d /s /c',
10 silly lifecycle   'bower install && gen-typescript-declarations --deleteExisting --outDir .' ]
11 silly lifecycle @polymer/marked-element@~update-types: Returned: code: 134  signal: null
12 info lifecycle @polymer/marked-element@~update-types: Failed to exec update-types script
13 verbose stack Error: @polymer/marked-element@ update-types: `bower install && gen-typescript-declarations --deleteExisting --outDir .`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\stramel\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\stramel\AppData\Roaming\nvm\v9.4.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid @polymer/marked-element@
15 verbose cwd C:\Users\stramel\Projects\GitHub\marked-element
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "update-types"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 134
22 error @polymer/marked-element@ update-types: `bower install && gen-typescript-declarations --deleteExisting --outDir .`
22 error Exit status 134
23 error Failed at the @polymer/marked-element@ update-types script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by mcarey1590** [comment]
I am having issues on windows as well
```
<--- Last few GCs --->

[12084:0000018E3285C8F0]   267847 ms: Mark-sweep 1416.2 (1496.6) -> 1416.2 (1496.6) MB, 2616.0 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000305F70A5EE1 <JSObject>
    2: applyScanners(aka applyScanners) [C:\Users\mcarey.TYR\AppData\Roaming\npm\node_modules\@polymer\gen-typescript-declarations\node_modules\polymer-analyzer\lib\javascript\javascript-document.js:~39] [pc=000001EB6EE4BDCB](this=000002E058682311 <undefined>,callbackName=0000004ADEC489A9 <String[19]: enterBlockStatement>,node=000003CA3CDEEA31 <Node map = 000002ADC91B5319>,parent=000003CA3CDEE...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewInternalizedStringImpl
 5: v8::internal::JSRegExp::New
 6: v8::internal::StringTable::LookupString
 7: v8::internal::StringTable::LookupString
 8: v8::internal::LookupIterator::LookupIterator
 9: v8::internal::LookupIterator::PropertyOrElement
10: v8::internal::ParserBase<v8::internal::Parser>::MarkLoopVariableAsAssigned
11: 000001EB6EC847A1
```

**Comment by homerjonathan** [comment]
I have had the same issues.  Memory out.  Seems to stop at the 

**Loading config from "gen-tsd.json".**

Running on **iron-dropdown** where the tool had obviously worked.

```
"@polymer/gen-typescript-declarations": "^1.2.0",
```

When I installed the version was changed to 1.2.1 which failed so I thought it might be that.  I went back to 1.2.0 and it still failed.

**Comment by aomarks** [comment]
I was able to reproduce this on Windows under the default Node settings, and found that increasing the heap size fixed the issue:

`NODE_OPTIONS="--max_old_space_size=4096" npm run update-types`

Let me know if this works for others too, and we can add a note to to the README.

Since this doesn't seem to have affected Mac or Linux users so far, it seems that either Analyzer uses more memory under Windows, or V8 behaves differently with respect to memory usage under Windows, or there are some different default flag values under Windows.

**Comment by homerjonathan** [comment]
Run with the new settings it now completes but there are no files output.

```
Loading config from "gen-tsd.json".
Deleting 0 existing d.ts files from C:\js_source\iron-dropdown
Writing type declarations to C:\js_source\iron-dropdown
```

I have a fairly fast machine Ryzen 1800X 3.85ghz 16Gb of memory, SSD (Windows 10 starts up in 2 seconds) and it still takes a good 2 minutes to run.  Memory of process runs at 2100MB with 8% CPU.  Not sure if there is something else going wrong other then just memory heap size.  Again this is just working on one component.

Any other suggestions?

**Comment by aomarks** [comment]
You're right, I didn't look at the output, and there is indeed nothing produced for iron-dropdown either under my Windows VM. Looks like there is a bug most likely to do with Windows path differences. I will investigate further on Monday.

If you don't have access to a Mac or Linux machine (you could try VirtualBox), let me know and I can generate the new types for your iron-dropdown PR so you can add them manually.

**Comment by aomarks** [comment]
Got it working, we were parsing `file://` URLs with Windows drive letters incorrectly. See the above linked PR. @homerjonathan if you want to get this working now, `git checkout` the `windows-paths` branch and `npm link` it into the repo you're working on.

In terms of performance, running on Windows does seem to be significantly slower and more memory intensive. Analyzing iron-location goes from seconds on Mac to minutes on Windows (granted on a VM for me, but looks like from the above report running natively on a fast machine too).

**Comment by homerjonathan** [comment]
Run the update still getting issues, takes about 15 - 20 minutes to run.

```
C:\js_source\iron-dropdown>npm run update-types

> @polymer/iron-dropdown@ update-types C:\js_source\iron-dropdown
> bower install && gen-typescript-declarations --deleteExisting --outDir .

Loading config from "gen-tsd.json".

<--- Last few GCs --->

[17992:000002812403BE70]  2485898 ms: Mark-sweep 4099.3 (4312.9) -> 4099.3 (4312.9) MB, 9016.7 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000A33AB25EE1 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [C:\Users\jhome\AppData\Roaming\npm\node_modules\@polymer\gen-typescript-declarations\node_modules\babylon\lib\index.js:839] [bytecode=00000063B26FAC81 offset=59](this=00000056BA102311 <undefined>,key=000003B1ACA38D59 <String[13]: containsOctal>)
    3: arguments adaptor frame: 3->1
    4: forEach(this=00000114F427E3F1 <JSArray[45]>)
    5: clone [C:...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewStruct
 5: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
 6: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
 7: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
 8: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
 9: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
10: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
11: std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Reallocate
12: 00000268963047A1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @polymer/iron-dropdown@ update-types: `bower install && gen-typescript-declarations --deleteExisting --outDir .`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @polymer/iron-dropdown@ update-types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jhome\AppData\Roaming\npm-cache\_logs\2018-03-18T16_07_32_227Z-debug.log
```

**Comment by stramel** [comment]
@homerjonathan did you run that with the `NODE_OPTIONS` set?

**Comment by homerjonathan** [comment]
Yes.  With and without.

**Comment by stramel** [comment]
Worked using the `windows-paths` branch for me.

**Steps that worked for me**

- clone `Polymer/gen-typescript-declarations`
- check out `windows-paths` branch
- run `npm i`
- run `npm run build`
- run `npm i -g .` to install globally the local version
- clone `PolymerElements/iron-dropdown`
- run `bower i`
- run `gen-typescript-declarations --deleteExisting --outDir .`

Didn't need the `NODE_OPTIONS` set. Ran in less than 30 seconds.

**Comment by homerjonathan** [comment]
Followed @stramel instructions.  Fine until the **npm run build** the script runs clean with a **rm** which not a valid windows command.

Instead **npm build:watch** seems to have created the lib directory etc.  This mean that the **npm i -g** and it has now successfully created the type declarations. 

Thanks for your help.

**Comment by stramel** [comment]
@homerjonathan What terminal are you using? I believe that was the difference between your build failing and mine working. I used Git Bash

**Comment by homerjonathan** [comment]
Windows cmd.
